_target_: beso.agents.diffusion_agents.k_diffusion.score_wrappers.GCDenoiser
_recursive_: false

sigma_data: ${sigma_data}


# either GCTimeScoreNetwork or TimeScoreNetwork FilmTimeScoreNetwork
inner_model:
  _target_: beso.agents.diffusion_agents.k_diffusion.score_mlps.FiLMTimeScoreNetwork
  _recursive_: false
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  hidden_dim: ${hidden_dim}
  goal_dim: ${goal_dim}
  embed_fn:
    _target_: beso.agents.diffusion_agents.k_diffusion.utils.return_time_sigma_embedding_model
     # 'GaussianFourier' 'FourierFeatures' or 'Sinusoidal'
    embedding_type: 'GaussianFourier'
    time_embed_dim: ${goal_dim} # ${t_dim} # ${hidden_dim}
    device: ${device}
  num_hidden_layers: ${num_hidden_layers}
  output_dim: ${action_dim}
  cond_mask_prob: ${cond_mask_prob}
  dropout: 0
  activation: "Mish"
  model_style: ${residual_style}
  use_spectral_norm: false
  use_norm: false
  norm_style: false
  device: ${device}
  goal_conditional: ${goal_conditioning}
